#!/usr/bin/env bash

if ! command -v dotnet &> /dev/null
then
    echo "dotnet command could not be found. Please install dotnet."
    read -p "Do you want to continue? (y/n) " -n 1 -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        echo "Exiting..."
        exit 1
    fi
fi

if ! command -v dotnet-csharpier &> /dev/null
then
    echo "Installing dotnet-csharpier..."
    dotnet tool install --global csharpier
fi

echo "Running dotnet-csharpier..."
dotnet-csharpier ./Assets/Scripts/

echo "dotnet-csharpier completed successfully."