#!/usr/bin/env bash

if [[ "$OSTYPE" != "msys" ]]; then
    echo "Skipping dotnet-csharpier because platform is not windows."
    exit 0
fi


if ! command -v dotnet &> /dev/null
then
    echo "dotnet command could not be found. Please install dotnet."
    exit 1
fi

if ! command -v dotnet-csharpier &> /dev/null
then
    echo "Installing dotnet-csharpier..."
    dotnet tool install --global csharpier
fi

echo "Running dotnet-csharpier..."
if ! dotnet-csharpier ./Assets/Scripts/; then
    echo "dotnet-csharpier failed!"
    exit 1
fi

git add ./Assets/Scripts/

echo "dotnet-csharpier completed successfully."