name: Unity C# Format

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    unity-csharp-format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install CSharpier
              run: |
                  dotnet tool install --global csharpier
                  echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

            - name: Verify Installation
              run: csharpier --version

            - name: Format C# Code
              run: csharpier --check .
