name: Unity C# Format

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    unity-csharp-format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install CSharpier
              run: |
                  dotnet tool install --global csharpier

            - name: Format C# Code (Push)
              run: |
                  dotnet-csharpier .
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git commit -am "chore: format C# code"
                  git push
